AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation de Tianguito."

Resources:
  TianguitoVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags:
      - Key: "Application"
        Value: Tianguito-stack
      - Key: "Name"
        Value: Tianguito

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.0.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Pub-1
          
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.0.1.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Pub-2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.2.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Priv-1
          
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.0.3.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Priv-2
  
  RoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
      - Key: "Name"
        Value: Tianguito_Route_Table
      VpcId:
        Ref: TianguitoVPC

  TianguitoGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
      - Key: "Name"
        Value: Tianguito-Gateway
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: 
        Ref: TianguitoGateway
      VpcId: 
        Ref: TianguitoVPC
  
  AssociationPub1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PublicSubnet1
  
  AssociationPub2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PublicSubnet2

  AssociationPriv1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PrivateSubnet1

  AssociationPriv2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PrivateSubnet2

  