AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation de Tianguito."

Resources:
  TianguitoVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags:
      - Key: "Application"
        Value: Tianguito-stack
      - Key: "Name"
        Value: Tianguito

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.0.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Pub-1
          
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.0.1.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Pub-2
