AWSTemplateFormatVersion: "2010-09-09"

Description: "Cloudformation de Tianguito."

Resources:
  TianguitoVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags:
      - Key: "Application"
        Value: Tianguito-stack
      - Key: "Name"
        Value: Tianguito

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.0.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Pub-1
          
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.0.1.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Pub-2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      CidrBlock: "10.0.2.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Priv-1
          
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      CidrBlock: "10.0.3.0/24"
      VpcId:
        Ref: TianguitoVPC
      Tags:
      - Key: "Name"
        Value: Tianguito-Priv-2
  
  RoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
      - Key: "Name"
        Value: Tianguito_Route_Table
      VpcId:
        Ref: TianguitoVPC

  TianguitoGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
      - Key: "Name"
        Value: Tianguito-Gateway
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: 
        Ref: TianguitoGateway
      VpcId: 
        Ref: TianguitoVPC
  
  AssociationPub1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PublicSubnet1
  
  AssociationPub2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PublicSubnet2

  AssociationPriv1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PrivateSubnet1

  AssociationPriv2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: 
        Ref: RoutingTable
      SubnetId: 
        Ref: PrivateSubnet2

  TianguitoACL1:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags: 
      - Key: "Name"
        Value: TianguitoACL1
      VpcId: 
        Ref: TianguitoVPC

  ACLEntryHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      NetworkAclId: 
        Ref: TianguitoACL1
      PortRange:
        From: 80
        To: 80
      Protocol: 6
      RuleAction: "allow"
      RuleNumber: 100
  
  ACLEntryHTTPS:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      NetworkAclId: 
        Ref: TianguitoACL1
      PortRange:
        From: 443
        To: 443
      Protocol: 6
      RuleAction: "allow"
      RuleNumber: 110

  ACLEntrySSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      NetworkAclId: 
        Ref: TianguitoACL1
      PortRange:
        From: 22
        To: 22
      Protocol: 6
      RuleAction: "allow"
      RuleNumber: 120
    
  ACLEntryRDP:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      NetworkAclId: 
        Ref: TianguitoACL1
      PortRange:
        From: 3389
        To: 3389
      Protocol: 6
      RuleAction: "allow"
      RuleNumber: 130
  
  ACLEntryDNSUDP:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      NetworkAclId: 
        Ref: TianguitoACL1
      PortRange:
        From: 53
        To: 53
      Protocol: 17
      RuleAction: "allow"
      RuleNumber: 140

  ACLEntryDNSUDPTCP:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      NetworkAclId: 
        Ref: TianguitoACL1
      PortRange:
        From: 53
        To: 53
      Protocol: 6
      RuleAction: "allow"
      RuleNumber: 150

  ACLAssociation1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: TianguitoACL1
      SubnetId: 
        Ref: PublicSubnet1

  ACLAssociation2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: TianguitoACL1
      SubnetId: 
        Ref: PublicSubnet2

  ACLAssociation3:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: TianguitoACL1
      SubnetId: 
        Ref: PrivateSubnet1
  
  ACLAssociation4:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: 
        Ref: TianguitoACL1
      SubnetId: 
        Ref: PrivateSubnet2

  