AWSTemplateFormatVersion: "2010-09-09"

Description: "Levantar una VPC"

Resources:
  TianguitoVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: "true"
      EnableDnsSupport: "true"
      Tags:
      - Key: "Application"
        Value: Tianguito-stack
      - Key: "Name"
        Value: Tianguito
